name: Convert Notebooks
on:
  push:
    paths: ['**.ipynb']
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install jupyter
        run: pip install jupyter
      
      - name: Convert notebooks to markdown
        run: |
          jupyter nbconvert --to markdown test.ipynb
      
      - name: Commit files
        run: |
          git config --local user.email "chris@trau.co"
          git config --local user.name "iTrauco"
          git add test.md
          git commit -m "Convert notebook to markdown" || echo "No changes to commit"
          git push